# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: HER CODE CAMP
email: info@hercodecamp.com
description: >- # this means to ignore newlines until "baseurl:"
  HER CODE CAMP is a free computer science weekend camp for senior high school students
  in the greater Toronto area who identify as a woman, non-binary, or transgender.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: hercodecamp

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-gallery-generator

gallery:
  dir: photos # Path to the gallery
  symlink: false # false: copy images into _site. true: create symbolic links (saves disk space)
  title: "Photos" # Title for gallery index page
  title_prefix: "Photos: " # Title prefix for gallery pages. Gallery title = title_prefix + gallery_name
  sort_field:
    "date_time" # How to sort galleries on the index page.
    # Possible values are: title, date_time, best_image
  thumbnail_size:
    x: 400 # max width of thumbnails (in pixels)
    y: 400 # max height of thumbnails (in pixels)
  # The following options are for individual galleries.
  # galleries:
  #   chile_trip:
  #     best_image: IMG_1068.JPG  # The image to show on the gallery index page. Defaults to the last image.
  #   japan_trip:
  #     best_image: IMG_0690.JPG
  #     name: "日本の旅"       # Defaults to directory name, replacing _ with spaces & capitalizing words.
  #   awesome_stuff:
  #     best_image: snaileo_gonzales.jpg
  #     sort_reverse: true    # Reverse sort images in gallery.
  #   secret_stuff:
  #     hidden: true          # Don't show this gallery on the index page. People must guess the URL.
  #   with_info:
  #     info:
  #       desc: "Gallery Description" # Info fields can be used in custom templates.

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
